<?php

namespace Database\Factories;

use App\Models\Blog;
use App\Models\Category;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Blog>
 */
class BlogFactory extends Factory
{
    protected $model = Blog::class;

    /**
     * Define the model's default state.
     * Note: `image` is NOT nullable. `content_ar`/`content_en` are NOT nullable.
     */
    public function definition(): array
    {
        $titlesAr = [
            'أحدث صيحات الموضة لهذا الموسم',
            'كيف تختارين الفستان المثالي',
            'نصائح للعناية بملابسك',
            'دليلك لاختيار الألوان المناسبة',
            'أزياء الربيع: ما الجديد؟',
            'تنسيق الملابس للمناسبات الخاصة',
            'العبايات العصرية: بين التقليد والحداثة',
            'اكسسوارات لا غنى عنها في خزانتك',
        ];

        return [
            'category_id'        => Category::inRandomOrder()->value('id'),
            'title_ar'           => fake()->randomElement($titlesAr) . ' ' . fake()->numberBetween(1, 100),
            'title_en'           => fake()->unique()->sentence(6),
            'slug_ar'            => null, // auto-generated by model boot
            'slug_en'            => null, // auto-generated by model boot
            'author'             => fake()->name(),
            'content_ar'         => fake()->paragraphs(5, true),
            'content_en'         => fake()->paragraphs(5, true),
            'meta_title_ar'      => null,
            'meta_title_en'      => null,
            'meta_description_ar'=> null,
            'meta_description_en'=> null,
            'meta_keywords_ar'   => null,
            'meta_keywords_en'   => null,
            'og_image'           => null,
            'image'              => 'blogs/placeholder-' . fake()->numberBetween(1, 10) . '.jpg',
            'detail_image'       => null,
            'is_active'          => true,
            'sort_order'         => fake()->numberBetween(0, 20),
            'published_at'       => fake()->dateTimeBetween('-6 months', 'now'),
            'tags'               => fake()->randomElements(['fashion', 'style', 'tips', 'trends', 'seasonal', 'accessories', 'luxury'], fake()->numberBetween(2, 4)),
        ];
    }

    /**
     * Indicate that the blog is inactive.
     */
    public function inactive(): static
    {
        return $this->state(fn () => [
            'is_active' => false,
        ]);
    }
}
