<?php

namespace Database\Factories;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Product>
 */
class ProductFactory extends Factory
{
    protected $model = Product::class;

    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        $nameEn = fake()->unique()->words(3, true);
        $nameAr = fake()->randomElement([
            'فستان أنيق', 'بلوزة صيفية', 'تنورة طويلة', 'بنطلون كلاسيكي',
            'عباية مطرزة', 'حقيبة جلدية', 'وشاح حريري', 'حذاء رياضي',
            'فستان سهرة', 'قميص قطني', 'جاكيت شتوي', 'سترة كاجوال',
        ]) . ' ' . fake()->numberBetween(1, 100);

        $price    = fake()->randomFloat(2, 20, 500);
        $oldPrice = fake()->boolean(40) ? round($price * fake()->randomFloat(2, 1.1, 1.5), 2) : null;

        return [
            'category_id'        => Category::inRandomOrder()->value('id') ?? Category::factory(),
            'name_ar'            => $nameAr,
            'name_en'            => ucwords($nameEn),
            'slug_ar'            => null, // auto-generated by model boot
            'slug_en'            => null, // auto-generated by model boot
            'description_ar'     => fake()->paragraphs(2, true),
            'description_en'     => fake()->paragraphs(2, true),
            'video_ar'           => null,
            'video_en'           => null,
            'meta_title_ar'      => null,
            'meta_title_en'      => null,
            'meta_description_ar'=> null,
            'meta_description_en'=> null,
            'meta_keywords_ar'   => null,
            'meta_keywords_en'   => null,
            'og_image'           => null,
            'price'              => $price,
            'old_price'          => $oldPrice,
            'image'              => 'products/placeholder-' . fake()->numberBetween(1, 10) . '.jpg',
            'sizes'              => fake()->randomElements(['XS', 'S', 'M', 'L', 'XL', 'XXL'], fake()->numberBetween(2, 5)),
            'colors'             => fake()->randomElements(['Red', 'Blue', 'Black', 'White', 'Green', 'Pink', 'Beige'], fake()->numberBetween(1, 4)),
            'brand'              => fake()->randomElement(['ZIZI', 'Elegance', 'Charm', 'Luna', null]),
            'stock'              => fake()->numberBetween(0, 100),
            'is_active'          => true,
            'is_featured'        => fake()->boolean(30),
            'sort_order'         => fake()->numberBetween(0, 50),
        ];
    }

    /**
     * Indicate that the product is featured.
     */
    public function featured(): static
    {
        return $this->state(fn () => [
            'is_featured' => true,
        ]);
    }

    /**
     * Indicate that the product is out of stock.
     */
    public function outOfStock(): static
    {
        return $this->state(fn () => [
            'stock' => 0,
        ]);
    }

    /**
     * Indicate that the product is inactive.
     */
    public function inactive(): static
    {
        return $this->state(fn () => [
            'is_active' => false,
        ]);
    }
}
